services:
    myservice:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        init: true
        working_dir: /workspace
        volumes:
            - ./:/workspace
        networks:
            # ネットワーク app-network に登録
            - app-network
        tty: true

    # plantumlサーバー
    plantuml-server:
        image: plantuml/plantuml-server
        ports:
            - "${PLANTUML_PORT:-8080}:8080"
        networks:
            # ネットワーク app-network に登録
            - app-network

networks:
    # ネットワーク app-network の設定
    app-network:
        driver: bridge
