services:
    myservice:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        init: true
        container_name: my_project
        working_dir: /workspace
        volumes:
            - ./:/workspace
        networks:
            # ネットワーク hoge-group に登録
            hoge-group:
        tty: true

    # plantumlサーバー
    plantuml-server:
        image: plantuml/plantuml-server
        container_name: plantuml-server
        ports:
            - 8080:8080
        networks:
            # ネットワーク hoge-group に登録
            hoge-group:
                ipv4_address: 172.22.0.3

networks:
    # ネットワーク hoge-group の設定
    hoge-group:
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
